---
services:
  mysql:
    image: mysql:8.0.27
    container_name: todo-mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: todo
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
