---
name: Check GitHub Actions
on:
  pull_request:
    branches:
      - main
    paths:
      - .github/**/*.yml
      - .github/**/*.yaml
permissions: read-all
jobs:
  actions-lint:
    permissions:
      checks: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-actionlint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          fail_on_error: true
